services:
  - type: web
    name: serverhub-api
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn serverhub.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    # Sağlık kontrolünü kaldırdık, böylece Render sadece portun açılmasını bekleyecek
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ORIGINS
        value: "https://snazzy-malabi-1c55bc.netlify.app"
      - key: DATABASE_URL
        fromDatabase:
          name: serverhub-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.0"

databases:
  - name: serverhub-db
    plan: free
    region: frankfurt
    databaseName: serverhub
    user: serverhub_user
